const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const { load, uuid } = require('./history-test-helpers.cjs')
const { createInterviewCompletionState, normalizeCompletionId } = load('lib/interviews/interview-completion-state.ts', {})
const payload = () => ({ interviewerKey:'f', role:'Engineer', company:'Example', level:'mid',
  interviewType:'technical', persona:'formal', language:'en', answers:[{q:'Q',a:'A'}],
  score:80, summary:'Summary', durationSeconds:60 })
function setup() { let calls=0; const state=createInterviewCompletionState(()=>{calls++;return uuid(1)}); return {state,calls:()=>calls} }
test('nonempty intent generates one UUID and retry reuses it',()=>{const h=setup();assert.equal(h.state.begin(payload().answers),uuid(1));assert.equal(h.state.begin(payload().answers),uuid(1));assert.equal(h.calls(),1)})
test('zero answers generate no identity',()=>{const h=setup();assert.equal(h.state.begin([]),null);assert.equal(h.calls(),0)})
test('payload is deeply frozen once and preserves object identity',()=>{const {state}=setup();state.begin(payload().answers);const p=state.freezePayload(payload());assert.ok(Object.isFrozen(p));assert.ok(Object.isFrozen(p.answers));assert.ok(Object.isFrozen(p.answers[0]));assert.strictEqual(state.freezePayload({...payload(),score:1}),p)})
test('live mutation cannot alter answers or duration',()=>{const {state}=setup(),live=payload();state.begin(live.answers);state.freezePayload(live);live.answers[0].a='Changed';live.answers.push({q:'New',a:'New'});live.durationSeconds=99;assert.equal(state.payload.answers.length,1);assert.equal(state.payload.answers[0].a,'A');assert.equal(state.payload.durationSeconds,60)})
test('evaluation failure leaves identity available with no payload',()=>{const {state}=setup();state.begin(payload().answers);assert.equal(state.payload,null);assert.equal(state.begin(payload().answers),uuid(1));assert.ok(state.freezePayload(payload()))})
test('POST failure does not discard frozen intent',()=>{const {state}=setup();state.begin(payload().answers);const p=state.freezePayload(payload());assert.equal(state.begin([{q:'Other',a:'Other'}]),uuid(1));assert.strictEqual(state.payload,p)})
test('success retains matching saved ID with optional replay flag',()=>{const {state}=setup();state.begin(payload().answers);assert.ok(state.acceptSaved({id:uuid(1),replayed:true}));assert.equal(state.savedId,uuid(1));assert.ok(state.acceptSaved({id:uuid(1)}))})
for(const response of [{id:uuid(2)},{id:'bad'},{id:uuid(1),replayed:'true'},null]) test('invalid saved response '+JSON.stringify(response),()=>{const {state}=setup();state.begin(payload().answers);assert.equal(state.acceptSaved(response),false);assert.equal(state.savedId,null)})
test('reset clears identity payload and saved ID',()=>{const {state}=setup();state.begin(payload().answers);state.freezePayload(payload());state.acceptSaved({id:uuid(1)});state.reset();assert.equal(state.completionId,null);assert.equal(state.payload,null);assert.equal(state.savedId,null)})
test('UUID validation requires v4 and normalizes case',()=>{assert.equal(normalizeCompletionId(uuid(10).toUpperCase()),uuid(10));for(const value of [undefined,12,' '+uuid(1),uuid(1).replace('-4000-','-1000-')]) assert.equal(normalizeCompletionId(value),null)})
test('helper has no browser storage',()=>{assert.doesNotMatch(fs.readFileSync(require('node:path').join(__dirname,'interview-completion-state.ts'),'utf8'),/localStorage|sessionStorage/)})
